//TEST CASE 3.
//Number should give an error as it exceeds limitations
//Test Case for (b) Integers larger than Integer.MAX VALUE
//Successfully detects an error for x=34567623456443
//Test Valid - ERROR

int func() {
    return 2;
}

void main () {
    int x;
    x=34567623456443;
}